### ISSUE TITLE
[bug] Wrong implementation of operator+= with negative numbers

### ISSUE THREAD

**Issue by ghost** [calccrypto/uint128_t#10]
When the `operator+=` is used with a signed integer it returns a wrong result when a negative amount is added as follows:

```
// g++ test.cpp uint128_t/uint128_t.cpp -g -o test -std=c++11
#include <iostream>
#include "uint128_t/uint128_t.h"

int main(int argc, char *argv[])
{
	int i = -1;
	uint128_t u128 = 10;
	uint64_t u64 = 10;
	
	u128 += i;
	u64 += i;
	std::cout << "u128=" << u128.str() << " u64=" << u64 << " TEST RESULT=" << (u128 == u64 ? "OK" : "FAIL") << std::endl;
	
	u128 = 10;
	u64 = 10;
	i = 1;
	u128 += i;
	u64 += i;
	std::cout << "u128=" << u128.str() << " u64=" << u64 << " TEST RESULT=" << (u128 == u64 ?  "OK" : "FAIL") << std::endl;
	
	return 0;
}
```
**output:**
```
u128=18446744073709551625 u64=9 TEST RESULT=FAIL
u128=11 u64=11 TEST RESULT=OK
```

It returns 18446744073709551625 instead of 9.

**Comment by calccrypto** [comment]
Hi. This is a known feature (?) of `uint128_t`. 

From the [README](https://github.com/calccrypto/uint128_t/blob/master/README.md#in-code):

> Be careful when initializing a uint128_t value. -1 does not create the value 2^128 - 1. Rather, it uses the built-in max unsigned value (probably 2^64 - 1).

If you change `i` to `uint128_t(-1, -1)`, you will get 9.

**Comment by ghost** [comment]
This is not about when I initialise a uint128_t. This is when I add a negative number to an existing uint128_t variable. In this situation it returns a wrong value. This is very dangerous bug.

**Comment by calccrypto** [comment]
Why are you using negative integers when using a `uintX_t` type?

~~The initialization comes from casting `i` to an `uint128_t` for [`operator+=`](https://github.com/calccrypto/uint128_t/blob/master/uint128_t.cpp#L238)~~

**Comment by ghost** [comment]
Why not? I need to add and subtract signed numbers to numbers uint128_t there is no difference between `145-140` and `145 + (- 140)` but two different results returns. This does not happen with `uint64_t`, `uint32_t`, etc then I think this is dangerous.

The same occurs when I use a negative number with all add and subtract operators `operator-=` `operator-` `operator+` `operator-=`

**A possible solution**
```
template <typename T, typename = typename std::enable_if<std::is_integral<T>::value, T>::type >
uint128_t operator+(const T & rhs) const{
    if(rhs>=0){
        return uint128_t((uint64_t)(UPPER + ((LOWER + rhs) < LOWER)), (uint64_t)(LOWER + rhs));
    }else{
		if(UPPER==0&&LOWER==0)
			return uint128_t((uint64_t)(-1),LOWER+rhs);
        return uint128_t((uint64_t)(UPPER + ((LOWER + rhs) > LOWER)), (uint64_t)(LOWER + rhs));
	}
}

template <typename T, typename = typename std::enable_if<std::is_integral<T>::value, T>::type >
uint128_t & operator+=(const T & rhs){
    *this = *this + rhs;
    return *this;
}

template <typename T, typename = typename std::enable_if<std::is_integral<T>::value, T>::type >
uint128_t operator-(const T & rhs) const{
    if(rhs>=0)
        return uint128_t((uint64_t)(UPPER - ((LOWER - rhs) > LOWER)), 	(uint64_t)(LOWER - rhs));
    else {
		return uint128_t((uint64_t)(UPPER + (LOWER > LOWER - rhs)),		(uint64_t)(LOWER - rhs));
	}
}

template <typename T, typename = typename std::enable_if<std::is_integral<T>::value, T>::type >
uint128_t & operator-=(const T & rhs){
    *this = *this - rhs;
    return *this;
}
```

**Comment by ghost** [comment]
I’m testing these changes, it seems to work ok. https://github.com/nilhcraiv/uint128_t/commit/79dde46ee407b80a4a891d1dc4ffc6aee1f96bee

**Comment by calccrypto** [comment]
Simpler fix with https://github.com/calccrypto/uint128_t/commit/92922b08312c39e5c65d7a82f3a5d9eb2b375229

**Comment by calccrypto** [comment]
Simpler fix with https://github.com/calccrypto/uint128_t/commit/ca53febb5f0b5eb954f2c27249b2024510c2a6d2

**Comment by pinanew** [comment]
@calccrypto I think you should add 
```
if (std::is_signed<T>::value) {
                if (rhs < 0) {
                    UPPER = -1;
                }
            }
```
in operator=(const T & rhs) too.
