### ISSUE TITLE
Promote to C++ standard

### ISSUE THREAD

**Issue by mcandre** [calccrypto/uint128_t#18]
How can we elevate this data type into the official C++ standard, so that 128 bit integers just work out of the box?

Note that clang / gcc already have 128 bit integers. This library could detect the compilers and automatically map the type accordingly.

The major compiler laggard is MSVC, which currently offers 64 bit integers. When the user is building with MSVC, then the 128 bit type can be implemented in terms of these high and low 64 bit integer types.

**Comment by calccrypto** [comment]
I'm glad that you like `uint128_t`. Why do you think that adding `uint128_t` to the C++ standard would be worth the effort over including/linking this repo? As you said, clang and gcc already know about `__uint128_t` and MSVC is likely to ignore the standard, so nothing will change.
