### ISSUE TITLE
any plans to add hash function

### ISSUE THREAD

**Issue by andreasdr** [calccrypto/uint128_t#19]
Hi,

nice one. Are there plans to add hash function to be able to use uint128_t with std::map, std::set, std::unordered_map, std::unordered_set?

Many thanx and

Best regards
Andreas

**Comment by calccrypto** [comment]
`operator<` should be enough for `std::map` and `std::set`. I have no plans to add a hash function for `std::unordered_map` and `std::unordered_set`.
