### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by jacob-navia** [calccrypto/uint128_t#20]
#include <iostream>
#include "uint256_t.h"

int main() {
    uint256_t a = uint256_t("1234567890987654321234567890123456789");
    uint256_t b = uint256_t("9876543212345678909876543212123456789");
    std::cout << (a + b) << std::endl;
    std::cout << (a * b) << std::endl;
    return 0;
}
OUTPUT
./a.out
237874615448440434220169051638465177762582290
36648625081468363373803679961248846042639268817955195957743481078122978838353
Correct answer
* a+b
11111111103333333231111111102246913578
* a*b
12193263123914037344916934337936290111422040471112635358890413056750190521

What I'm doing wrong?

Thanks

**Comment by calccrypto** [comment]
At some point, I accidentally accepted a pull request that reads strings only as hex digits. I plan on fixing this in the coming weeks.

**Comment by jacob-navia** [comment]
OK. Thank you very much for your quick answer.

Jacob

**Comment by calccrypto** [comment]
I have removed the constructors that take in strings only. Now, you have to provide the base for the string e.g. `uint256_t("1234567890987654321234567890123456789", 10)`.
