### ISSUE TITLE
uint128_t name usage

### ISSUE THREAD

**Issue by noloader** [calccrypto/uint128_t#22]
I hope I am not splitting too many hairs, but the `_t` suffix is reserved for the language by the C standard. You should not use it for your type. I've always observed it in C++ programs, too.

You should probably put your type in a namespace, too. I can imagine what the collisions are going to look like.

**Comment by calccrypto** [comment]
Normally, I would have placed the class in a namespace, but this was intended as a drop in replacement for `uintX_t` types, and I wanted it to look the same as using the standard built in types/
