### ISSUE TITLE
How to use this in a project?

### ISSUE THREAD

**Issue by jason0597** [calccrypto/uint128_t#7]
Hi, sorry if this comes off as noobish but I don't understand how I can use this in a small project.
E.g. if I have a simple `main.cpp` with nothing but a `main()` in it, how is it included? Do you copy all the `.cpp` and `.h` files in the repository to the root of your project, `#include` the correct `.h` file and then use the classes/functions that are provided? Do all the bitwise operations work just like as they would in normal integers (e.g. u64)?

**Comment by calccrypto** [comment]
Hi. `uint128_t` should still be usable as it was before 7ca379c7ea112b00a0c45e2dc7a16f362443e8fd. In your source file , you should be able to just do: 

```c++
#include <iostream>
#include "uint128_t.h"

int main() {
    uint128_t a = 1;
    uint128_t b = 2;
    std::cout << (a | b) << std::endl;
    return 0;
}
```

You will need every `uint128_t.*` file.

When you compile, you just need to link the source in, whether as-is (`g++ -std=c++11 main.cpp uint128_t.cpp`), or as an [object file](https://github.com/calccrypto/uint128_t/blob/master/tests/Makefile#L45), or a library.

Bitwise operators work as standard unsigned integer types. If you find something that does not work as expected, please let me know/fix it (and make a pull request).

**Comment by jason0597** [comment]
Thanks it works!
Maybe add this in the readme?

**Comment by calccrypto** [comment]
How's b3fc05bf15b08037fd0a1f7a1d98be06ffb88d0e?
